version: '3.5'


services:
  bugtrackerfrontend:
    container_name: bugtrackerfrontend
    image: ${DOCKER_REGISTRY-}bugtrackerfrontend
    ports:
      - "8443:443"
    build:
      context: .
      dockerfile: BugTrackerFrontend/Dockerfile

  bugtrackerapi:
    container_name: bugtrackerapi
    image: ${DOCKER_REGISTRY-}bugtrackerapi
    ports:
      - "8180:80"
    build:
      context: .
      dockerfile: BugTrackerAPI/Dockerfile
      
  bugdb:
    container_name: bugdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1401:1433"
    environment:
      MSSQL_SA_PASSWORD: "hello123HELLO!"
      ACCEPT_EULA: "Y"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    environment:
      - ConnectionStrings__BugDbContext=Server=bugdb,1433;User ID=SA;Password=hello123HELLO!
    volumes:
      - .:/BugTracker
    working_dir: /BugTracker
    command:
      [
        "dotnet",
        "test",
        "./BugTrackerAPI.IntegrationTests/BugTrackerAPI.IntegrationTests.csproj"
      ]
